unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'onedark'
set -g @tmux2k-icons-only false 
set -g @tmux2k-left-plugins "git cpu ram"
set -g @tmux2k-right-plugins "battery time"
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark' # or 'light'
#
set -g @plugin 'christoomey/vim-tmux-navigator' 

# set -g @plugin 'tmux-plugins/tmux-sensible'

# keep this line at the very bottom
run '~/.tmux/plugins/tpm/tpm'
